[client]
showSidebarNavigation = false

[browser]
gatherUsageStats = false

[server]
headless = true
enableXsrfProtection = true
maxUploadSize = 10
runOnSave = false

address = "127.0.0.1"
port = 8501

[runner]
magicEnabled = false
fastReruns = true
